import { Product, Category, HeroSlide, ShippingMethod, SiteSettings, Coupon, Review } from '@/types';

export const defaultSiteSettings: SiteSettings = {
  site_name: 'Ceylon Times',
  tagline: 'Authentic Sri Lankan Craftsmanship & Living Heritage',
  logo_url: '/logo-black.png',
  logo_inverted_url: '/logo-white.png',
  favicon_url: '/favicon.png',
  contact_email: 'concierge@ceylontimes.lk',
  contact_phone: '+94 11 255 0199',
  business_address: '42 Galle Face Promenade, Colombo 03, Sri Lanka 00300',
  currency_code: 'LKR',
  currency_symbol: 'Rs.',
  tax_rate: 12.0,
  tax_inclusive: false,
  announcement_bar_active: true,
  announcement_bar_text: 'Complimentary island-wide delivery on orders over Rs.7,500 — Use code CEYLON22 ✦ Free gift wrapping available',
  announcement_bar_link: '/products',
  announcement_bar_color: '#0A0A0F',
  social_instagram: 'https://instagram.com',
  social_facebook: 'https://facebook.com',
  social_twitter: 'https://twitter.com',
  social_tiktok: 'https://tiktok.com',
  social_youtube: 'https://youtube.com',
};

export const defaultHeroSlides: HeroSlide[] = [
  {
    id: 'hero-1',
    image_url: '/sigiriya.jpg',
    heading: 'Sigiriya Citadel & Sovereign Heritage',
    heading_si: 'සීගිරිය අභිමානය හා හෙළ උරුමය',
    subheading: 'Acquire bespoke royal handcrafted jewelry, sacred temple brass artifacts, and museum-grade masterworks directly from the artisan lineages of Sri Lanka.',
    subheading_si: 'පාරම්පරික ශ්‍රී ලාංකීය කලා ශිල්පීන්ගේ අද්විතීය නිමවුම්, රාජකීය ස්වර්ණාභරණ හා පිත්තල නිර්මාණ දැන්ම ලබාගන්න.',
    cta_text: 'Acquire Heritage Art',
    cta_text_si: 'උරුමය මිලදී ගන්න',
    cta_link: '/products?category=sacred-living',
    badge: '✦ Royal Ancient Citadel Collection',
    badge_si: '✦ රාජකීය සීගිරි පෞරාණික උරුමය',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'hero-2',
    image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=2000&q=85',
    heading: 'Single-Estate Highland Ceylon Tea',
    heading_si: 'නුවරඑළියේ අග්‍රගන්‍ය සිලෝන් තේ අස්වැන්න',
    subheading: 'Hand-plucked Silver Tips and artisanal reserve black teas from the mist-veiled mountain slopes of Nuwara Eliya and Ella.',
    subheading_si: 'නුවරඑළිය සහ ඇල්ල කඳුකරයේ අතින් නෙළූ සුවඳවත් සිලෝන් රිදී තේ දළු සහ විශේෂ තේ නිෂ්පාදන එකතුව රසවිඳින්න.',
    cta_text: 'Buy Reserve Tea',
    cta_text_si: 'තේ ඇණවුම් කරන්න',
    cta_link: '/products?category=tea',
    badge: '✦ Nuwara Eliya & Ella Reserve',
    badge_si: '✦ නුවරඑළිය සහ ඇල්ල තේ අස්වැන්න',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'hero-3',
    image_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=2000&q=85',
    heading: 'Certified Ratnapura Ceylon Sapphires',
    heading_si: 'රත්නපුරයේ සහතිකලත් නිල් මැණික් හා ස්වර්ණාභරණ',
    subheading: 'Ethically mined royal blue sapphires, alexandrites, and padparadscha gems certified by the National Gem and Jewellery Authority of Sri Lanka.',
    subheading_si: 'ජාතික මැණික් හා ස්වර්ණාභරණ අධිකාරියේ සහතිකලත් සැබෑ රත්නපුර නිල් මැණික් සහ නිර්මාණාත්මක පළඳනා එකතුව.',
    cta_text: 'Shop Ceylon Sapphires',
    cta_text_si: 'මැණික් මිලදී ගන්න',
    cta_link: '/products?category=jewellery',
    badge: '✦ National Gem Authority Certified',
    badge_si: '✦ ජාතික මැණික් අධිකාරියේ සහතිකලත්',
    sort_order: 3,
    is_active: true,
  },
  {
    id: 'hero-4',
    image_url: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=2000&q=85',
    heading: 'Sacred Temple Brass & Traditional Woodcraft',
    heading_si: 'පාරම්පරික පිත්තල හා අම්බලන්ගොඩ දැව කැටයම්',
    subheading: 'Ceremonial cast-brass oil lamps, hand-carved protective Raksha masks, and authentic artisan woodcraft to bring harmony to your sanctuary.',
    subheading_si: 'ශ්‍රී ලංකාවේ පාරම්පරික කැටයම් ශිල්පීන් අතින් නිමවූ පූජනීය පිත්තල පහන්, දැවමය මුහුණු සහ හස්ත කර්මාන්ත නිර්මාණ.',
    cta_text: 'Explore Handicrafts',
    cta_text_si: 'කලා නිර්මාණ බලන්න',
    cta_link: '/products?category=sacred-living',
    badge: '✦ Heritage Temple Brasscraft',
    badge_si: '✦ පාරම්පරික විහාරස්ථාන පිත්තල කලාව',
    sort_order: 4,
    is_active: true,
  },
  {
    id: 'hero-5',
    image_url: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?auto=format&fit=crop&w=2000&q=85',
    heading: 'Kandyan Handloom Silks & Beeralu Lace',
    heading_si: 'උඩරට අත්යන්ත්‍ර පට රෙදි හා ගාලු බීරළු රේන්ද',
    subheading: 'Woven on wooden village frame looms across centuries-old traditions. Breathable Sri Lankan organic cottons, pure silks, and artisanal batiks.',
    subheading_si: 'පාරම්පරික අත්යන්ත්‍ර මඟින් වියන ලද උසස් තත්ත්වයේ සේද සාරි, බීරළු රේන්ද සහ බතික් ඇඳුම් ආයිත්තම් දැන්ම ඇණවුම් කරන්න.',
    cta_text: 'Buy Handlooms',
    cta_text_si: 'රෙදිපිළි මිලදී ගන්න',
    cta_link: '/products?category=textiles',
    badge: '✦ Dumbara Village Handloom',
    badge_si: '✦ දුම්බර ගම්මානයේ අත්යන්ත්‍ර වියමන',
    sort_order: 5,
    is_active: true,
  },
];

export const defaultCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Ceylon Jewellery',
    slug: 'jewellery',
    description: 'Hand-set Ceylon sapphires and alexandrites in oxidised silver from Galle Fort craftsmen.',
    image_url: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    sort_order: 1,
    created_at: '2024-01-01',
    product_count: 3,
  },
  {
    id: 'cat-2',
    name: 'Handloom Textiles',
    slug: 'textiles',
    description: 'Kandyan silk sarees, Beeralu lace, and hand-batik sarongs woven on traditional frame looms.',
    image_url: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    sort_order: 2,
    created_at: '2024-01-01',
    product_count: 4,
  },
  {
    id: 'cat-3',
    name: 'Sacred Living',
    slug: 'sacred-living',
    description: 'Temple brass oil lamps, Kolam pottery vessels, and hand-carved ebony ceremonial pieces.',
    image_url: 'https://images.unsplash.com/photo-1604147706283-d7119b5b822c?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    sort_order: 3,
    created_at: '2024-01-01',
    product_count: 3,
  },
  {
    id: 'cat-4',
    name: 'Ayurveda & Botanicals',
    slug: 'ayurveda',
    description: 'Cold-pressed coconut oil serums, Ceylon cinnamon extracts, and hand-rolled herbal elixirs.',
    image_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    sort_order: 4,
    created_at: '2024-01-01',
    product_count: 3,
  },
  {
    id: 'cat-5',
    name: 'Ceylon Tea Reserve',
    slug: 'tea',
    description: 'Single-estate Silver Tips, aged Pu-erh blends, and ceremonial first-flush Nuwara Eliya.',
    image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    sort_order: 5,
    created_at: '2024-01-01',
    product_count: 2,
  },
];

export const defaultProducts: Product[] = [
  {
    id: 'prod-1',
    title: 'Ceylon Blue Sapphire Pendant — Galle Fort Silver',
    slug: 'ceylon-blue-sapphire-pendant',
    description: '<p>A breathtaking 2.8ct natural unheated Ceylon blue sapphire — certified by the Gem & Jewellery Authority of Sri Lanka — set by master silversmiths of Galle Fort in oxidised 92.5 sterling silver with hand-engraved lotus motifs.</p><p>Each stone is individually selected from Ratnapura\'s legendary gem gravels and accompanied by a provenance certificate. Delivered in a handcrafted ebony box lined with Kandyan silk.</p>',
    category_id: 'cat-1',
    price: 98500,
    sale_price: 85000,
    sku: 'JEW-SAP-01',
    stock_quantity: 5,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    tags: ['featured', 'new-arrival', 'jewellery', 'best-seller'],
    rating: 4.9,
    review_count: 38,
    total_orders: 64,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
    images: [
      {
        id: 'img-1-1',
        image_url: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Ceylon Blue Sapphire Pendant',
      },
      {
        id: 'img-1-2',
        image_url: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=85',
        sort_order: 2,
        alt_text: 'Sapphire Pendant Detail',
      },
    ],
    options: [
      {
        id: 'opt-1-1',
        name: 'Chain Length',
        sort_order: 1,
        values: [
          { id: 'v-1', value: '18 inch', sort_order: 1 },
          { id: 'v-2', value: '20 inch', sort_order: 2 },
          { id: 'v-3', value: '24 inch', sort_order: 3 },
        ],
      },
    ],
  },
  {
    id: 'prod-2',
    title: 'Kandyan Silk Saree — Royal Midnight Weave',
    slug: 'kandyan-silk-saree-royal-midnight',
    description: '<p>Woven over twelve days on traditional hand-operated Dumbara frame looms using pure mulberry silk and 22-carat gold zari thread. Features the iconic Kandyan "Salu" border motif drawn from ancient temple ceiling paintings of Degaldoruwa Raja Maha Viharaya.</p><p>Each saree bears a handwritten weaver certificate with the artisan\'s thumbprint — a cherished heirloom-grade textile connecting you to over 800 years of Sri Lankan royal court tradition.</p>',
    category_id: 'cat-2',
    price: 52000,
    sale_price: null,
    sku: 'TEX-SIL-02',
    stock_quantity: 8,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    tags: ['featured', 'best-seller', 'textiles'],
    rating: 5.0,
    review_count: 52,
    total_orders: 110,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-02-15T10:00:00Z',
    images: [
      {
        id: 'img-2-1',
        image_url: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Kandyan Silk Saree',
      },
      {
        id: 'img-2-2',
        image_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85',
        sort_order: 2,
        alt_text: 'Saree Gold Zari Detail',
      },
    ],
    options: [
      {
        id: 'opt-2-1',
        name: 'Colour',
        sort_order: 1,
        values: [
          { id: 'v-6', value: 'Royal Midnight Blue', sort_order: 1 },
          { id: 'v-7', value: 'Crimson Temple Red', sort_order: 2 },
          { id: 'v-8', value: 'Forest Sage Green', sort_order: 3 },
        ],
      },
    ],
  },
  {
    id: 'prod-3',
    title: 'Hand-batik Linen Kurta — Elephant Motif Collection',
    slug: 'hand-batik-linen-kurta-elephant',
    description: '<p>Artisan-dyed using traditional wax-resist batik technique with natural indigo, jackfruit bark, and turmeric dyes on organic Lankan linen. Features the sacred elephant motif — symbol of wisdom and strength in Sri Lankan Buddhist tradition.</p><p>Ethically made in Ambalangoda by second-generation batik craftspeople who inherited the craft from Dutch colonial-era masters.</p>',
    category_id: 'cat-2',
    price: 14500,
    sale_price: 11500,
    sku: 'TEX-KUR-03',
    stock_quantity: 16,
    track_inventory: true,
    allow_backorders: true,
    status: 'active',
    tags: ['new-arrival', 'textiles', 'featured'],
    rating: 4.8,
    review_count: 24,
    total_orders: 87,
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-10T10:00:00Z',
    images: [
      {
        id: 'img-3-1',
        image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Hand-batik Linen Kurta',
      },
      {
        id: 'img-3-2',
        image_url: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1200&q=85',
        sort_order: 2,
        alt_text: 'Batik Pattern Detail',
      },
    ],
    options: [
      {
        id: 'opt-3-1',
        name: 'Size',
        sort_order: 1,
        values: [
          { id: 'v-9', value: 'Small', sort_order: 1 },
          { id: 'v-10', value: 'Medium', sort_order: 2 },
          { id: 'v-11', value: 'Large', sort_order: 3 },
          { id: 'v-12', value: 'XL', sort_order: 4 },
        ],
      },
    ],
  },
  {
    id: 'prod-4',
    title: 'Diya Nilambe — Ceremonial Brass Oil Lamp Triptych',
    slug: 'diya-nilambe-ceremonial-brass-lamp',
    description: '<p>A triptych of temple-style Diya oil lamps cast in 90% brass using the lost-wax (cire perdue) method by hereditary craftsmen of Kandy\'s Vishnu Devale tradition. Stands 38cm tall with lotusform base and a multi-wick cup accommodating pure coconut oil or ghee.</p><p>Used in puja ceremonies and meditation sanctuaries throughout Sri Lanka for over 1,200 years. Arrives presented in handmade palmyra reed packaging.</p>',
    category_id: 'cat-3',
    price: 32000,
    sale_price: null,
    sku: 'SAC-DIA-04',
    stock_quantity: 6,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    tags: ['sacred-living', 'best-seller', 'featured'],
    rating: 4.9,
    review_count: 19,
    total_orders: 55,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
    images: [
      {
        id: 'img-4-1',
        image_url: 'https://images.unsplash.com/photo-1604147706283-d7119b5b822c?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Ceremonial Brass Oil Lamp',
      },
      {
        id: 'img-4-2',
        image_url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=1200&q=85',
        sort_order: 2,
        alt_text: 'Oil Lamp Detail Close-up',
      },
    ],
    options: [],
  },
  {
    id: 'prod-5',
    title: 'Ceylon Ayurveda Body Oil — Nelli & Coconut Elixir',
    slug: 'ceylon-ayurveda-body-oil-nelli',
    description: '<p>Cold-pressed virgin Lunuwila coconut oil infused over 21 days with hand-harvested Nelli (Indian Gooseberry), King Coconut extract, Venivel turmeric, and Sri Lankan sandalwood chips. A traditional Panchakarma preparation recipe preserved since the 12th-century Dambadenia Kingdom.</p><p>Certified organic by the Export Agriculture Department of Sri Lanka. Packaged in hand-blown Galle glass with hand-carved coconut shell stopper.</p>',
    category_id: 'cat-4',
    price: 8500,
    sale_price: 7200,
    sku: 'AYU-OIL-05',
    stock_quantity: 22,
    track_inventory: true,
    allow_backorders: true,
    status: 'active',
    tags: ['ayurveda', 'featured', 'new-arrival'],
    rating: 5.0,
    review_count: 41,
    total_orders: 132,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
    images: [
      {
        id: 'img-5-1',
        image_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Ayurveda Body Oil Bottle',
      },
      {
        id: 'img-5-2',
        image_url: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1200&q=85',
        sort_order: 2,
        alt_text: 'Ayurveda Oil Ingredients',
      },
    ],
    options: [
      {
        id: 'opt-5-1',
        name: 'Size',
        sort_order: 1,
        values: [
          { id: 'v-16', value: '100ml', sort_order: 1 },
          { id: 'v-17', value: '200ml', sort_order: 2 },
        ],
      },
    ],
  },
  {
    id: 'prod-6',
    title: 'Nuwara Eliya Silver Tips Imperial — Limited Flush',
    slug: 'nuwara-eliya-silver-tips-imperial',
    description: '<p>Hand-plucked at 6,000 feet elevation on the misty plateaux of Lovers\' Leap Estate, Nuwara Eliya — the "Champagne of teas" region. Only the youngest silver-haired buds are selected during the rare and precious April first-flush season.</p><p>This lot of 60 grams represents just 3.2kg of bud harvest from 1.2 hectares. Produces a luminous amber liquor with champagne effervescence, white peach, and honeysuckle notes. Supplied in hand-turned dumbara lacquerware canisters.</p>',
    category_id: 'cat-5',
    price: 18500,
    sale_price: null,
    sku: 'TEA-SIL-06',
    stock_quantity: 15,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    tags: ['tea', 'featured', 'new-arrival'],
    rating: 4.9,
    review_count: 27,
    total_orders: 103,
    created_at: '2024-03-05T10:00:00Z',
    updated_at: '2024-03-05T10:00:00Z',
    images: [
      {
        id: 'img-6-1',
        image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Nuwara Eliya Silver Tips Tea',
      },
      {
        id: 'img-6-2',
        image_url: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=1200&q=85',
        sort_order: 2,
        alt_text: 'Ceylon Tea Ceremony',
      },
    ],
    options: [
      {
        id: 'opt-6-1',
        name: 'Weight',
        sort_order: 1,
        values: [
          { id: 'v-18', value: '25g', sort_order: 1 },
          { id: 'v-19', value: '60g — Lacquerware Canister', sort_order: 2 },
          { id: 'v-20', value: '125g — Gift Set', sort_order: 3 },
        ],
      },
    ],
  },
  {
    id: 'prod-7',
    title: 'Alexandrite Cat\'s Eye Ring — Rarity Grade I',
    slug: 'alexandrite-cats-eye-ring',
    description: '<p>A phenomenal 1.65ct natural alexandrite cat\'s-eye chrysoberyl from Matara — one of the world\'s rarest gemstone varieties. Displays dramatic colour-change from blue-green in daylight to raspberry-violet under incandescent light, with a sharp silver chatoyant eye across the centre.</p><p>GIA-certified. Set in 18ct recycled yellow gold with micro-pavé diamond shoulders. Includes GJAL (Gem & Jewellery Authority Lanka) certificate and independent valuation report at Rs.210,000.</p>',
    category_id: 'cat-1',
    price: 165000,
    sale_price: null,
    sku: 'JEW-ALE-07',
    stock_quantity: 2,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    tags: ['featured', 'jewellery'],
    rating: 5.0,
    review_count: 8,
    total_orders: 9,
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
    images: [
      {
        id: 'img-7-1',
        image_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Alexandrite Cat Eye Ring',
      },
    ],
    options: [
      {
        id: 'opt-7-1',
        name: 'Ring Size (US)',
        sort_order: 1,
        values: [
          { id: 'v-21', value: '5', sort_order: 1 },
          { id: 'v-22', value: '6', sort_order: 2 },
          { id: 'v-23', value: '7', sort_order: 3 },
          { id: 'v-24', value: '8', sort_order: 4 },
        ],
      },
    ],
  },
  {
    id: 'prod-8',
    title: 'Heritage Field Watch — Ceylon Moonstone Dial',
    slug: 'heritage-field-watch-marine-bronze',
    description: '<p>A hand-assembled field watch celebrating Sri Lanka\'s legendary moonstone tradition. The dial is set with a genuine polished Meetiyagoda moonstone — translucent with an adularescence sheen like a full moon reflected in the Indian Ocean. Marine-grade bronze case will develop a rich patina over time.</p><p>Swiss ETA 2824-2 automatic movement with 38-hour power reserve. Water resistant to 5ATM. Strap crafted from tanned buffalo hide with padded palm-frond texture.</p>',
    category_id: 'cat-1',
    price: 42500,
    sale_price: 37500,
    sku: 'WAT-MON-08',
    stock_quantity: 9,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    tags: ['featured', 'new-arrival', 'jewellery', 'best-seller'],
    rating: 4.8,
    review_count: 31,
    total_orders: 67,
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-02-20T10:00:00Z',
    images: [
      {
        id: 'img-8-1',
        image_url: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Heritage Field Watch Moonstone',
      },
      {
        id: 'img-8-2',
        image_url: 'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=85',
        sort_order: 2,
        alt_text: 'Watch Caseback Detail',
      },
    ],
    options: [
      {
        id: 'opt-8-1',
        name: 'Strap Colour',
        sort_order: 1,
        values: [
          { id: 'v-25', value: 'Havana Tan', sort_order: 1 },
          { id: 'v-26', value: 'Midnight Black', sort_order: 2 },
        ],
      },
    ],
  },
  {
    id: 'prod-9',
    title: 'Kolam Stoneware Tea Service — Peacock Glaze',
    slug: 'kolam-stoneware-tea-service',
    description: '<p>Hand-thrown in Yapahuwa by master potter Priyantha Wickramasinghe using ancient Kolam ceremonial pottery techniques. Each chawan bowl features a reactive peacock-tail glaze in teal, gold, and deep cobalt — unique per firing. Includes woven coconut-shell tea tray and bamboo tea scoop.</p>',
    category_id: 'cat-3',
    price: 9800,
    sale_price: 8200,
    sku: 'SAC-KOL-09',
    stock_quantity: 14,
    track_inventory: true,
    allow_backorders: true,
    status: 'active',
    tags: ['sacred-living', 'featured'],
    rating: 5.0,
    review_count: 33,
    total_orders: 89,
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-02-10T10:00:00Z',
    images: [
      {
        id: 'img-9-1',
        image_url: 'https://images.unsplash.com/photo-1548781-75-f2d3-bf02c?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Kolam Stoneware Tea Set',
      },
    ],
    options: [],
  },
  {
    id: 'prod-10',
    title: 'Cinnamon & Black Pepper Herbal Body Scrub',
    slug: 'ceylon-cinnamon-pepper-body-scrub',
    description: '<p>Exfoliating body scrub blended from true Ceylon cinnamon bark powder, fresh-ground Matale black pepper, raw Kithul jaggery, and king coconut shell micro-granules. Stimulates circulation, refines skin texture, and leaves a warm spiced fragrance for hours.</p><p>Formulated by Ayurvedic physician Dr. Sandya Karunaratne using recipes from the 15th-century Sinhala medicinal text Ath Vaidya Maha Sangrahaya. Vegan and cruelty-free.</p>',
    category_id: 'cat-4',
    price: 3800,
    sale_price: null,
    sku: 'AYU-SCR-10',
    stock_quantity: 50,
    track_inventory: true,
    allow_backorders: true,
    status: 'active',
    tags: ['ayurveda', 'new-arrival'],
    rating: 4.7,
    review_count: 58,
    total_orders: 240,
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
    images: [
      {
        id: 'img-10-1',
        image_url: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Cinnamon Body Scrub',
      },
    ],
    options: [
      {
        id: 'opt-10-1',
        name: 'Size',
        sort_order: 1,
        values: [
          { id: 'v-27', value: '150g', sort_order: 1 },
          { id: 'v-28', value: '300g', sort_order: 2 },
        ],
      },
    ],
  },
  {
    id: 'prod-11',
    title: 'Beeralu Lace Table Runner — Heritage Lace Pattern',
    slug: 'beeralu-lace-table-runner',
    description: '<p>Hand-crafted using the intricate Portuguese-influenced Beeralu bobbin-lace technique practiced exclusively in Galle District, Sri Lanka. Each runner represents 40+ hours of work by skilled lacemakers from the Stitch & Thread Women\'s Cooperative, Ambalangoda.</p>',
    category_id: 'cat-2',
    price: 6500,
    sale_price: null,
    sku: 'TEX-LAC-11',
    stock_quantity: 18,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    tags: ['textiles', 'best-seller'],
    rating: 4.9,
    review_count: 29,
    total_orders: 76,
    created_at: '2024-01-25T10:00:00Z',
    updated_at: '2024-01-25T10:00:00Z',
    images: [
      {
        id: 'img-11-1',
        image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Beeralu Lace Table Runner',
      },
    ],
    options: [
      {
        id: 'opt-11-1',
        name: 'Length',
        sort_order: 1,
        values: [
          { id: 'v-29', value: '90cm', sort_order: 1 },
          { id: 'v-30', value: '150cm', sort_order: 2 },
          { id: 'v-31', value: '220cm', sort_order: 3 },
        ],
      },
    ],
  },
  {
    id: 'prod-12',
    title: 'Dimbula Valley High-Grown Orthodox — Collector\'s Tin',
    slug: 'dimbula-valley-orthodox-collectors-tin',
    description: '<p>A robust high-grown orthodox black tea from Dimbula Valley, Uva Province — prized for its bold muscatel flavour and deep mahogany liquor. Hand-rolled and withered using traditional century-old Orthodox manufacturing, producing a leaf with complex malt, dark cherry, and mountain herbs.</p><p>Packed in a hand-painted Sinhala calligraphy collector\'s tin by artist Nishantha Senanayake from Kandy Art Guild.</p>',
    category_id: 'cat-5',
    price: 7500,
    sale_price: null,
    sku: 'TEA-DIM-12',
    stock_quantity: 28,
    track_inventory: true,
    allow_backorders: true,
    status: 'active',
    tags: ['tea', 'best-seller'],
    rating: 4.8,
    review_count: 44,
    total_orders: 156,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    images: [
      {
        id: 'img-12-1',
        image_url: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=1200&q=85',
        sort_order: 1,
        alt_text: 'Dimbula Valley Orthodox Tea Tin',
      },
    ],
    options: [
      {
        id: 'opt-12-1',
        name: 'Quantity',
        sort_order: 1,
        values: [
          { id: 'v-32', value: '100g tin', sort_order: 1 },
          { id: 'v-33', value: '200g tin', sort_order: 2 },
          { id: 'v-34', value: '500g bulk', sort_order: 3 },
        ],
      },
    ],
  },
];

export const defaultCoupons: Coupon[] = [
  {
    id: 'coup-1',
    code: 'CEYLON22',
    type: 'percentage',
    value: 12,
    min_order_amount: 7500,
    usage_limit: 500,
    per_customer_limit: 1,
    times_used: 134,
    valid_from: '2024-01-01T00:00:00Z',
    valid_to: '2026-12-31T23:59:59Z',
    is_active: true,
  },
  {
    id: 'coup-2',
    code: 'FIRSTORDER',
    type: 'percentage',
    value: 15,
    min_order_amount: 5000,
    usage_limit: 200,
    per_customer_limit: 1,
    times_used: 87,
    valid_from: '2024-01-01T00:00:00Z',
    valid_to: '2026-06-30T23:59:59Z',
    is_active: true,
  },
  {
    id: 'coup-3',
    code: 'COLOMBO500',
    type: 'fixed',
    value: 500,
    min_order_amount: 3000,
    usage_limit: null,
    per_customer_limit: null,
    times_used: 0,
    valid_from: '2024-01-01T00:00:00Z',
    valid_to: null,
    is_active: true,
  },
];

export const defaultShippingMethods: ShippingMethod[] = [
  {
    id: 'ship-1',
    name: 'Island Standard Delivery',
    description: 'Delivered island-wide within 3–5 business days via registered post.',
    price: 350,
    estimated_days: '3–5 business days',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'ship-2',
    name: 'Island Express Courier',
    description: 'Priority door-to-door delivery within 1–2 business days via DHL / Kapruka.',
    price: 750,
    estimated_days: '1–2 business days',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'ship-3',
    name: 'International Air Express',
    description: 'DHL Worldwide to 120+ countries. 5–8 business days with full tracking.',
    price: 3500,
    estimated_days: '5–8 business days',
    is_active: true,
    sort_order: 3,
  },
];

export const defaultReviews: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-1',
    reviewer_name: 'Anushka Bandara',
    reviewer_email: 'anushka@gmail.com',
    rating: 5,
    title: 'Absolutely breathtaking — heritage quality',
    body: 'Ordered the Ceylon sapphire pendant for my grandmother\'s 80th birthday. The gem quality is extraordinary — deep cornflower blue with silk-like inclusions visible only under magnification. The Galle Fort silverwork is intricate and sturdy. True heirloom quality.',
    is_approved: true,
    created_at: '2024-03-20T08:00:00Z',
  },
  {
    id: 'rev-2',
    product_id: 'prod-2',
    reviewer_name: 'Priyantha Dissanayake',
    reviewer_email: 'priyantha@yahoo.com',
    rating: 5,
    title: 'Our village artisans are so talented — this proves it',
    body: 'The Kandyan silk saree is beyond words. The gold zari work catches the light beautifully. My wife wore it at our daughter\'s perahera ceremony and received so many compliments. The weaver\'s certificate with thumbprint made it extra meaningful.',
    is_approved: true,
    created_at: '2024-03-15T10:30:00Z',
  },
  {
    id: 'rev-3',
    product_id: 'prod-5',
    reviewer_name: 'Sarah Mitchell',
    reviewer_email: 'sarah.m@outlook.com',
    rating: 5,
    title: 'The best body oil I\'ve ever used — sent from Colombo to London',
    body: 'I discovered Ceylon Times while visiting Sri Lanka last year. The Nelli & Coconut oil has transformed my skin. The packaging is beautiful — the hand-blown glass bottle and coconut shell stopper are works of art themselves. Shipping was faster than expected.',
    is_approved: true,
    created_at: '2024-03-10T14:00:00Z',
  },
  {
    id: 'rev-4',
    product_id: 'prod-6',
    reviewer_name: 'Hiroshi Tanaka',
    reviewer_email: 'htanaka@gmail.com',
    rating: 5,
    title: 'The finest tea I have ever tasted — from Japan with gratitude',
    body: 'I have been drinking tea for 40 years across Japan, Taiwan, and China. This Nuwara Eliya Silver Tips is something truly special — the champagne effervescence and white peach notes are unlike anything I\'ve tasted. The lacquerware canister is exquisite.',
    is_approved: true,
    created_at: '2024-03-05T09:15:00Z',
  },
];
